### PR TITLE
Fixes #14. Track registered items using a `WeakSet`

### LINKED ISSUE #14: Grid works incorrectly without `<React.StrictMode>`
Version: `ruuri v2.0.0`
The grid works incorrectly in production or dev mode without `<React.StrictMode>`.
The following error is printed to the console. 

image

[Codesandbox](https://codesandbox.io/p/sandbox/festive-lederberg-5lkmzh?file=%2Fsrc%2Fmain.tsx%3A7%2C23) to reproduce the issue. You can add/remove strict mode to see the error in the console.
Do you think there's a workaround for this?

Thank you for your hard work!

### PR DESCRIPTION
**Pull request by romanstetsyk**
In this PR, tracking registered items is implemented using WeakSet.

Fixes #14

### CODE REVIEW

**Comment by romanstetsyk** [comment]
Rebased from the latest upstream/main, as requested

**Comment by vingeraycn** [comment]
You're come!

**Comment by vingeraycn** [comment]
I merged your branch into main, Thanks for your contribution again! Roman Stetsyk. 
Have a nice day~

**Comment by romanstetsyk** [comment]
Thanks for merging!

**Pull request merged**
